# Generated by Django 4.1.5 on 2023-02-14 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='используется в sms оповещения, формат 89123456789', max_length=20, null=True, verbose_name='Рабочий телефон')),
                ('departament', models.SmallIntegerField(blank=True, choices=[(0, 'Дизайнеры')], null=True, verbose_name='Отдел')),
                ('is_locking', models.BooleanField(default=False, help_text='Пользователь заблокирован на время, он можете входить, но не может получать новые замеры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('user',),
            },
        ),
    ]
