# Generated by Django 4.1.5 on 2023-02-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reckoning',
            options={'verbose_name': 'Просчёт', 'verbose_name_plural': 'Просчёты'},
        ),
        migrations.AlterField(
            model_name='reckoning',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата'),
        ),
    ]
