# Generated by Django 4.1.5 on 2023-02-03 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0002_alter_reckoning_options_alter_reckoning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reckoning',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='froze_designer', to=settings.AUTH_USER_MODEL, verbose_name='Дизайнер'),
        ),
    ]
