# Generated by Django 4.1.5 on 2023-02-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_reckoning_specification_and_more'),
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOfferpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperfacades', models.CharField(max_length=250, verbose_name='Фасады (верх)')),
                ('lowerfacades', models.CharField(max_length=250, verbose_name='Фасады (низ)')),
                ('tabletop', models.CharField(max_length=250, verbose_name='Столешница')),
                ('other', models.CharField(max_length=250, verbose_name='Прочее')),
                ('accessories', models.CharField(max_length=250, verbose_name='Фурнитура')),
                ('sketch', models.ImageField(upload_to='sketch/%Y/%m/%d/', verbose_name='Эскиз')),
                ('costcalculation', models.FileField(upload_to='costcalculation/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('reckoning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.reckoning', verbose_name='Коммерческое предложение')),
            ],
            options={
                'verbose_name': 'КП для кухни',
                'verbose_name_plural': 'КП для кухонь',
            },
        ),
        migrations.DeleteModel(
            name='Offerpage',
        ),
    ]
