# Generated by Django 4.1.5 on 2023-02-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_kitchenofferpage_delete_offerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenofferpage',
            name='total_discounted_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='kitchenofferpage',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
